version: '3'
 
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db
             
  db:
    image: postgres:10-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app