version: '3'
 
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python3 manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db
             
  db:
    image: postgres:11-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"
  celery:
    restart: always
    build:
      context: .
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app
  daphne:
    build:
      context: .
    command: daphne -b 0.0.0.0 -p 8001 backend.asgi:application
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    links:
      - redis
      - app