# Generated by Django 4.1 on 2022-08-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_chatgroupnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroupnotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
