# Generated by Django 4.1 on 2022-08-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_chatgroupnotification_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroupnotification',
            name='type',
            field=models.CharField(choices=[('Message', 'Message'), ('IsCalling', 'IsCalling'), ('MissedCall', 'MissedCall')], default='Message', max_length=16),
        ),
        migrations.DeleteModel(
            name='AppNotification',
        ),
    ]
