# Generated by Django 4.1 on 2022-08-25 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0004_alter_chatgroupnotification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClassNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Event', 'Message'), ('Story', 'IsCalling'), ('Announcement', 'MissedCall')], default='Announcement', max_length=16)),
                ('title', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
                ('qty_missed', models.IntegerField(default=1)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_class_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
