# Generated by Django 4.0.4 on 2022-06-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_notificationmode_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='in_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='school.parent'),
        ),
    ]
