# Generated by Django 4.1 on 2022-08-26 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0005_schoolclassnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsettings',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_settings', to='school.parent'),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_received_notification', models.BooleanField(default=True)),
                ('new_story_notification', models.BooleanField(default=False)),
                ('new_announcement_notification', models.BooleanField(default=False)),
                ('new_event_notification', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
