# Generated by Django 4.0.4 on 2022-06-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_assignee_in_portfolio_alter_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.schoolclass'),
        ),
        migrations.AlterField(
            model_name='event',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='school.schoolclass'),
        ),
        migrations.AlterField(
            model_name='story',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='school.schoolclass'),
        ),
    ]
