# Generated by Django 4.0.4 on 2022-06-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
