# Generated by Django 4.0.4 on 2022-06-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='school.student'),
        ),
        migrations.AlterField(
            model_name='assignmentmedia',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_media', to='school.assignee'),
        ),
    ]
