# Generated by Django 4.0.4 on 2022-06-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_assignee_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='helpers_required',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='helper',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpers', to='school.event'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helping_at', to='school.parent'),
        ),
    ]
