# Generated by Django 4.0.4 on 2022-06-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_chatgroup_owner_alter_groupmember_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='owner',
            new_name='group_owner',
        ),
    ]
