# Generated by Django 4.0.4 on 2022-06-28 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0014_rename_owner_chatgroup_group_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('user', 'group')},
        ),
    ]
