# Generated by Django 4.0.4 on 2022-06-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_groupmember_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.parent')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite_code', to='school.student')),
            ],
        ),
    ]
