# Generated by Django 4.0.4 on 2022-06-29 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.parent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.groupmember'),
        ),
        migrations.AlterField(
            model_name='parentsettings',
            name='notification_mode',
            field=models.OneToOneField(default='App', on_delete=django.db.models.deletion.SET_DEFAULT, to='school.notificationmode'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='school.parent'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school'),
        ),
    ]
