# Generated by Django 4.0.4 on 2022-06-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_parent_user_alter_parentsettings_parent_and_more'),
        ('school', '0004_alter_parent_user_and_more'),
        ('school', '0017_alter_invitecode_parent_alter_message_sender_and_more'),
    ]

    operations = [
    ]
