# Generated by Django 4.0.4 on 2022-07-04 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_parent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsettings',
            name='notification_mode',
            field=models.ForeignKey(default='App', on_delete=django.db.models.deletion.SET_DEFAULT, to='school.notificationmode'),
        ),
    ]
