# Generated by Django 4.0.4 on 2022-07-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_alter_student_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.schoolclass'),
        ),
        migrations.AlterUniqueTogether(
            name='assignee',
            unique_together={('student', 'assignment')},
        ),
    ]
