# Generated by Django 4.0.4 on 2022-07-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_alter_message_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
