# Generated by Django 4.0.4 on 2022-07-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_story_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
