# Generated by Django 4.0.4 on 2022-07-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_groupmember_connected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='connected',
            new_name='connected_to_call',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='connected_to_chat',
            field=models.BooleanField(default=False),
        ),
    ]
