# Generated by Django 4.0.4 on 2022-07-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_rename_connected_groupmember_connected_to_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_pictures/'),
        ),
    ]
