# Generated by Django 4.0.4 on 2022-07-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storymedia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='storymedia',
            name='file',
        ),
        migrations.AddField(
            model_name='storymedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_media/'),
        ),
    ]
