# Generated by Django 4.0.4 on 2022-07-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_remove_storymedia_description_remove_storymedia_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymedia',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_images', to='school.story'),
        ),
    ]
