# Generated by Django 4.0.4 on 2022-07-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_alter_storymedia_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='response_format',
            field=models.CharField(choices=[('Text', 'Text'), ('Image', 'Image'), ('Video', 'Video')], default='Text', max_length=16),
        ),
    ]
