# Generated by Django 4.0.4 on 2022-07-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_assignment_response_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assignment_media/')),
                ('video', models.FileField(blank=True, null=True, upload_to='assignment_media/')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_responses', to='school.assignee')),
            ],
        ),
        migrations.DeleteModel(
            name='AssignmentMedia',
        ),
    ]
