# Generated by Django 4.0.4 on 2022-07-27 08:10

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_assignmentresponse_delete_assignmentmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='code',
            field=models.CharField(default=school.models.create_assignment_code, max_length=32, unique=True),
        ),
    ]
