# Generated by Django 4.0.4 on 2022-07-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_alter_assignment_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignee',
            old_name='in_portfolio',
            new_name='submitted',
        ),
    ]
