# Generated by Django 4.0.4 on 2022-07-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_rename_in_portfolio_assignee_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='school.assignment'),
        ),
    ]
