# Generated by Django 4.0.4 on 2022-07-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_alter_assignee_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='invite_code',
        ),
    ]
